version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: express-ts-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mooodle
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - express-network

volumes:
  mongodb_data:
    driver: local

networks:
  express-network:
    driver: bridge